# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-03 18:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mathanapp', '0002_image_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='category',
            new_name='namecat',
        ),
    ]
